spring:
  application:
    name: User-Service
  profiles:
    active: dev
  config:
    import: application-prod.yml
  cache:
    type: redis
    cache-names: redis-cache
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5436/stroy1click
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  flyway:
    url: jdbc:postgresql://localhost:5436/stroy1click
    user: postgres
    password: password
    baseline-on-migrate: true
  messages:
    basename: messages
    encoding: UTF-8
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        acks: all
        enable.idempotence: true
        delivery.timeout.ms: 120000
        linger.ms: 0
        request.timeout.ms: 30000
        max.in.flight.requests.per.connection: 4
        spring.json.add.type.headers: true
  threads:
    virtual:
      enabled: true

otel:
  sdk:
    disabled: true

server:
  port: 6060

resilience4j:
  ratelimiter:
    instances:
      userLimiter:
        limitForPeriod: 100
        limitRefreshPeriod: 1s
  circuitbreaker:
    instances:
      userClient:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 120s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        ignore-exceptions:
          - ru.stroy1click.common.exception.NotFoundException
          - ru.stroy1click.common.exception.ValidationException

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

url:
  user: http://localhost:8080/api/v1/users

jwt:
  secret: 5367566B5970337336762342342342341139792F4123F452811482B4D6251655468576D5A71347437