create schema if not exists confirmation_code;

create table if not exists confirmation_code.confirmation_codes(
                                                                   id bigint generated by default as identity primary key ,
                                                                   code int not null ,
                                                                   expiration_date timestamp not null ,
                                                                   type varchar not null ,
                                                                   user_email varchar not null
);
-- Test: ConfirmationCodeControllerIT confirmEmail_ValidCode_ConfirmsEmail()
-- Description: подтверждение почты
insert into confirmation_code.confirmation_codes(code, expiration_date, type, user_email) values (1234567, '2029-06-15 14:30:45.123456', 'EMAIL','jeffbezos@gmail.com');

-- Test: ConfirmationCodeControllerIT recreate_ExistingCode_RegeneratesConfirmationCode()
-- Description: пересоздание кода подтверждения
insert into confirmation_code.confirmation_codes(code, expiration_date, type, user_email) values (1234567, '2029-06-15 14:30:45.123456', 'EMAIL','donaldtrump@gmail.com');

-- Test: ConfirmationCodeControllerIT updatePassword_ValidCodeAndPasswords_UpdatesPassword()
-- Description: обновление пароля
insert into confirmation_code.confirmation_codes(code, expiration_date, type, user_email) values (1234567, '2029-06-15 14:30:45.123456', 'PASSWORD','paveldurovtg@gmail.com');

-- Test: ConfirmationCodeControllerIT create_InvalidEmail_ReturnsValidationError()
-- Description: попытка подтвердить почту с неверным кодом подтверждения
insert into confirmation_code.confirmation_codes(code, expiration_date, type, user_email) values (1234567, '2029-06-15 14:30:45.123456', 'EMAIL','johnkennedy@gmail.com');

-- Test: ConfirmationCodeControllerIT confirmEmail_InvalidCode_ReturnsError()
-- Description: попытка обновить пароль с неверным кодом подтверждения
insert into confirmation_code.confirmation_codes(code, expiration_date, type, user_email) values (1234567, '2029-06-15 14:30:45.123456', 'EMAIL','tomholland@gmail.com');

-- Test: ConfirmationCodeControllerIT updatePassword_PasswordsDoNotMatch_ReturnsError()
-- Description: попытка обновить пароль при разных паролях(newPassword != confirmPassword)
insert into confirmation_code.confirmation_codes(code, expiration_date, type, user_email) values (1234567, '2029-06-15 14:30:45.123456', 'PASSWORD','ryangosling@gmail.com');